name: roastcalc
description: "Do math, get roasted!"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^3.1.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.4
  flutter_dotenv: ^6.0.0
  google_generative_ai: ^0.4.7
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "appLogo/appLogo.png"
  adaptive_icon_foreground: "appLogo/appLogo_foreground.png"
  adaptive_icon_background: "appLogo/appLogo_background.png"
  adaptive_icon_monochrome: "appLogo/appLogo_monochrome.png"



flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/no_history_dark_mode.png
    - lib/assets/no_history_light_mode.png

  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: lib/assets/JetBrainsMono.ttf
